/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as BlogRouteImport } from './routes/blog/route'
import { Route as UpdateBlogRouteImport } from './routes/UpdateBlog/route'
import { Route as IndexImport } from './routes/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as BlogProfileImport } from './routes/blog/profile'
import { Route as BlogMonthImport } from './routes/blog/month'
import { Route as BlogMainImport } from './routes/blog/main'
import { Route as BlogAllImport } from './routes/blog/all'
import { Route as BlogIdImport } from './routes/blog/$id'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticateddashboardSeniorDashboardImport } from './routes/_authenticated/(dashboard)/seniorDashboard'
import { Route as AuthenticateddashboardMiddleDashboardImport } from './routes/_authenticated/(dashboard)/middleDashboard'
import { Route as AuthenticateddashboardJuniorDashboardImport } from './routes/_authenticated/(dashboard)/juniorDashboard'
import { Route as AuthenticateddashboardClientDashboardImport } from './routes/_authenticated/(dashboard)/clientDashboard'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const BlogRouteRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const UpdateBlogRouteRoute = UpdateBlogRouteImport.update({
  id: '/UpdateBlog',
  path: '/UpdateBlog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogProfileRoute = BlogProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogMonthRoute = BlogMonthImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogMainRoute = BlogMainImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogAllRoute = BlogAllImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogIdRoute = BlogIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRouteRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticateddashboardSeniorDashboardRoute =
  AuthenticateddashboardSeniorDashboardImport.update({
    id: '/(dashboard)/seniorDashboard',
    path: '/seniorDashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticateddashboardMiddleDashboardRoute =
  AuthenticateddashboardMiddleDashboardImport.update({
    id: '/(dashboard)/middleDashboard',
    path: '/middleDashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticateddashboardJuniorDashboardRoute =
  AuthenticateddashboardJuniorDashboardImport.update({
    id: '/(dashboard)/juniorDashboard',
    path: '/juniorDashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticateddashboardClientDashboardRoute =
  AuthenticateddashboardClientDashboardImport.update({
    id: '/(dashboard)/clientDashboard',
    path: '/clientDashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/UpdateBlog': {
      id: '/UpdateBlog'
      path: '/UpdateBlog'
      fullPath: '/UpdateBlog'
      preLoaderRoute: typeof UpdateBlogRouteImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/all': {
      id: '/blog/all'
      path: '/all'
      fullPath: '/blog/all'
      preLoaderRoute: typeof BlogAllImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/main': {
      id: '/blog/main'
      path: '/main'
      fullPath: '/blog/main'
      preLoaderRoute: typeof BlogMainImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/month': {
      id: '/blog/month'
      path: '/month'
      fullPath: '/blog/month'
      preLoaderRoute: typeof BlogMonthImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/profile': {
      id: '/blog/profile'
      path: '/profile'
      fullPath: '/blog/profile'
      preLoaderRoute: typeof BlogProfileImport
      parentRoute: typeof BlogRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof BlogRouteImport
    }
    '/_authenticated/(dashboard)/clientDashboard': {
      id: '/_authenticated/(dashboard)/clientDashboard'
      path: '/clientDashboard'
      fullPath: '/clientDashboard'
      preLoaderRoute: typeof AuthenticateddashboardClientDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(dashboard)/juniorDashboard': {
      id: '/_authenticated/(dashboard)/juniorDashboard'
      path: '/juniorDashboard'
      fullPath: '/juniorDashboard'
      preLoaderRoute: typeof AuthenticateddashboardJuniorDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(dashboard)/middleDashboard': {
      id: '/_authenticated/(dashboard)/middleDashboard'
      path: '/middleDashboard'
      fullPath: '/middleDashboard'
      preLoaderRoute: typeof AuthenticateddashboardMiddleDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(dashboard)/seniorDashboard': {
      id: '/_authenticated/(dashboard)/seniorDashboard'
      path: '/seniorDashboard'
      fullPath: '/seniorDashboard'
      preLoaderRoute: typeof AuthenticateddashboardSeniorDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface BlogRouteRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
  BlogAllRoute: typeof BlogAllRoute
  BlogMainRoute: typeof BlogMainRoute
  BlogMonthRoute: typeof BlogMonthRoute
  BlogProfileRoute: typeof BlogProfileRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogIdRoute: BlogIdRoute,
  BlogAllRoute: BlogAllRoute,
  BlogMainRoute: BlogMainRoute,
  BlogMonthRoute: BlogMonthRoute,
  BlogProfileRoute: BlogProfileRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticateddashboardClientDashboardRoute: typeof AuthenticateddashboardClientDashboardRoute
  AuthenticateddashboardJuniorDashboardRoute: typeof AuthenticateddashboardJuniorDashboardRoute
  AuthenticateddashboardMiddleDashboardRoute: typeof AuthenticateddashboardMiddleDashboardRoute
  AuthenticateddashboardSeniorDashboardRoute: typeof AuthenticateddashboardSeniorDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticateddashboardClientDashboardRoute:
    AuthenticateddashboardClientDashboardRoute,
  AuthenticateddashboardJuniorDashboardRoute:
    AuthenticateddashboardJuniorDashboardRoute,
  AuthenticateddashboardMiddleDashboardRoute:
    AuthenticateddashboardMiddleDashboardRoute,
  AuthenticateddashboardSeniorDashboardRoute:
    AuthenticateddashboardSeniorDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/UpdateBlog': typeof UpdateBlogRouteRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/all': typeof BlogAllRoute
  '/blog/main': typeof BlogMainRoute
  '/blog/month': typeof BlogMonthRoute
  '/blog/profile': typeof BlogProfileRoute
  '/blog/': typeof BlogIndexRoute
  '/clientDashboard': typeof AuthenticateddashboardClientDashboardRoute
  '/juniorDashboard': typeof AuthenticateddashboardJuniorDashboardRoute
  '/middleDashboard': typeof AuthenticateddashboardMiddleDashboardRoute
  '/seniorDashboard': typeof AuthenticateddashboardSeniorDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/UpdateBlog': typeof UpdateBlogRouteRoute
  '': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/all': typeof BlogAllRoute
  '/blog/main': typeof BlogMainRoute
  '/blog/month': typeof BlogMonthRoute
  '/blog/profile': typeof BlogProfileRoute
  '/blog': typeof BlogIndexRoute
  '/clientDashboard': typeof AuthenticateddashboardClientDashboardRoute
  '/juniorDashboard': typeof AuthenticateddashboardJuniorDashboardRoute
  '/middleDashboard': typeof AuthenticateddashboardMiddleDashboardRoute
  '/seniorDashboard': typeof AuthenticateddashboardSeniorDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/UpdateBlog': typeof UpdateBlogRouteRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/all': typeof BlogAllRoute
  '/blog/main': typeof BlogMainRoute
  '/blog/month': typeof BlogMonthRoute
  '/blog/profile': typeof BlogProfileRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/(dashboard)/clientDashboard': typeof AuthenticateddashboardClientDashboardRoute
  '/_authenticated/(dashboard)/juniorDashboard': typeof AuthenticateddashboardJuniorDashboardRoute
  '/_authenticated/(dashboard)/middleDashboard': typeof AuthenticateddashboardMiddleDashboardRoute
  '/_authenticated/(dashboard)/seniorDashboard': typeof AuthenticateddashboardSeniorDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/UpdateBlog'
    | '/blog'
    | ''
    | '/signin'
    | '/signup'
    | '/profile'
    | '/blog/$id'
    | '/blog/all'
    | '/blog/main'
    | '/blog/month'
    | '/blog/profile'
    | '/blog/'
    | '/clientDashboard'
    | '/juniorDashboard'
    | '/middleDashboard'
    | '/seniorDashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/UpdateBlog'
    | ''
    | '/signin'
    | '/signup'
    | '/profile'
    | '/blog/$id'
    | '/blog/all'
    | '/blog/main'
    | '/blog/month'
    | '/blog/profile'
    | '/blog'
    | '/clientDashboard'
    | '/juniorDashboard'
    | '/middleDashboard'
    | '/seniorDashboard'
  id:
    | '__root__'
    | '/'
    | '/UpdateBlog'
    | '/blog'
    | '/_authenticated'
    | '/signin'
    | '/signup'
    | '/_authenticated/profile'
    | '/blog/$id'
    | '/blog/all'
    | '/blog/main'
    | '/blog/month'
    | '/blog/profile'
    | '/blog/'
    | '/_authenticated/(dashboard)/clientDashboard'
    | '/_authenticated/(dashboard)/juniorDashboard'
    | '/_authenticated/(dashboard)/middleDashboard'
    | '/_authenticated/(dashboard)/seniorDashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UpdateBlogRouteRoute: typeof UpdateBlogRouteRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UpdateBlogRouteRoute: UpdateBlogRouteRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/UpdateBlog",
        "/blog",
        "/_authenticated",
        "/signin",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/UpdateBlog": {
      "filePath": "UpdateBlog/route.tsx"
    },
    "/blog": {
      "filePath": "blog/route.tsx",
      "children": [
        "/blog/$id",
        "/blog/all",
        "/blog/main",
        "/blog/month",
        "/blog/profile",
        "/blog/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/profile",
        "/_authenticated/(dashboard)/clientDashboard",
        "/_authenticated/(dashboard)/juniorDashboard",
        "/_authenticated/(dashboard)/middleDashboard",
        "/_authenticated/(dashboard)/seniorDashboard"
      ]
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/blog/$id": {
      "filePath": "blog/$id.tsx",
      "parent": "/blog"
    },
    "/blog/all": {
      "filePath": "blog/all.tsx",
      "parent": "/blog"
    },
    "/blog/main": {
      "filePath": "blog/main.tsx",
      "parent": "/blog"
    },
    "/blog/month": {
      "filePath": "blog/month.tsx",
      "parent": "/blog"
    },
    "/blog/profile": {
      "filePath": "blog/profile.tsx",
      "parent": "/blog"
    },
    "/blog/": {
      "filePath": "blog/index.tsx",
      "parent": "/blog"
    },
    "/_authenticated/(dashboard)/clientDashboard": {
      "filePath": "_authenticated/(dashboard)/clientDashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(dashboard)/juniorDashboard": {
      "filePath": "_authenticated/(dashboard)/juniorDashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(dashboard)/middleDashboard": {
      "filePath": "_authenticated/(dashboard)/middleDashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(dashboard)/seniorDashboard": {
      "filePath": "_authenticated/(dashboard)/seniorDashboard.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
